name: CFML TestBox Test Runner
on: [push]
jobs:
 check:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v2
   - uses: Ortus-University/ou-testbox-action@6cb927a6180320a436ccf8c1518a02c237684942
