name: CFML TestBox Test Runner
on: [push]
jobs:
 check:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v2
   - uses: Ortus-University/ou-testbox-action@b3145d9e7b38f88463adb59587aa6b7f6e89944d
